Substitute current rust interface for Jira=> Goji with jira_query
aixigo/PREvant pull request #132
Opened 2023-07-11 11:13 UTC by AnumDastgir

This will enable PREvant to interact with Jira in a functional manner just like before.

2023-07-11 11:22 UTC, samuchila commented on api/Cargo.toml
> +jira_query = "1.2"
There is a new version available already. It would be great to use the latest version from the get go.

```suggestion
jira_query = "1.3.0"
```

2023-07-11 11:29 UTC, samuchila requested changes
Thanks for the contribution @AnumDastgir . The changes looks good. Based on previous interactions with Marc, I have added a few comments. Please try to address them.

2023-07-11 11:29 UTC, samuchila commented on api/src/models/ticket_info.rs
> +    fn from(issues: Issue) -> Self {
Since we are referring to a single issue, its preferred to call it issue itself.
```suggestion
    fn from(issue: Issue) -> Self {
```

2023-07-11 11:29 UTC, samuchila commented on api/src/tickets.rs
This seems like a formatting issue causing the whole file to be shown as changed. Usually only the lines you have touched should be shown in changes.
I would suggest to perform a rustfmt on the file along with clippy for the code you have written only.

2023-07-11 11:29 UTC, samuchila commented on api/Cargo.toml
> +jira_query = "1.2"
There is a new version available already. It would be great to use the latest version from the get go.
```suggestion
jira_query = "1.3.0"
```

2023-07-12 09:47 UTC, AnumDastgir commented on api/src/tickets.rs
Thanks a lot @samuchila for such constructive suggestions. I'll make the changes suggested.

2023-07-31 07:02 UTC, schrieveslaach approved these changes
I looked at the code and I tested your change. Works as before. Thanks a lot.

I approved your PR. However, please squash your commits into one commit while keeping your first commit message. Then I'll merge your PR.

2023-08-04 14:05 UTC, merged