URL Generation Was Not Taking Forwarded Header Into Account
aixigo/PREvant pull request #139
Opened 2023-11-09 02:10 UTC by AnumDastgir

Added testcases to ensure a successful URL generation after adding the code to deal with x-forwarded-header values.
Fixes #109

2023-11-09 08:12 UTC, schrieveslaach requested changes
Thanks for creating these test and I'm very pleased to see them.

I created a set of suggestion comments to your PR. Please, check and apply them.

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/models/request_info.rs
> +        let forwarded_host = request.headers().get_one("x-forwarded-host");
This part of the code has been already merged in your previous PR #137. I think you have to rebase…

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn with_invalid_headers() {
`with_invalid_headers`, `with_invalid_value_space_as_host`, and `with_invalid_value_backslash_as_host` test all the same equivalence class and thus more then one variant is sufficient.

A bit dated, but [this video](https://www.youtube.com/watch?v=P1Hv2sUPKeM) explains equivalence partitioning and what I mean by equivalence class.

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn with_valid_values() {
This test tests nothing new, no new equivalence class… So the tests at the beginning should have you covered.

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn without_prefer_header() {
Typo or copy paste error?

```suggestion
        async fn bad_request_without_host_header() {
```

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn without_prefer_header2() {
Seems to be the same test as above. Please, remove.

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +                .mount("/api/apps", crate::apps::apps_routes());
This block appears to be the very same in a lot of tests. You could create a function for it.

```suggestion
            let rocket = set_up_rochet_with_dummy_infrastructure_and_a_running_app();
```

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn host_header_response_with_xforwardedproto_and_other_default_values(
apply suggestions from `host_header_response_with_xforwardedhost_xforwardedproto_and_xforwardedport`

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn host_header_response_with_xforwardedhost_and_other_default_values(
apply suggestions from `host_header_response_with_xforwardedhost_xforwardedproto_and_xforwardedport`

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn host_header_response_with_xforwardedport_and_default_values(
apply suggestions from `host_header_response_with_xforwardedhost_xforwardedproto_and_xforwardedport`

2023-11-09 08:12 UTC, schrieveslaach commented on api/src/apps/routes.rs
> +        async fn host_header_response_with_all_default_values(
apply suggestions from `host_header_response_with_xforwardedhost_xforwardedproto_and_xforwardedport`

2023-11-29 11:10 UTC, AnumDastgir commented
Thank you so much for such detailed suggestions. I have implemented and committed them.

2023-11-30 11:29 UTC, schrieveslaach approved these changes
Changes look good to me. Please, squash your commits into one and then I'll merge it to main.

2023-12-01 09:52 UTC, merged