Bootstrap Companions in Kubernetes Environments
aixigo/PREvant pull request #156
Opened 2024-01-11 10:03 UTC by schrieveslaach

This commit introduces the configuration `bootstrapping.containers` which provides a way to parse the configuration of application wide companions because the current available configuration of companions if quite limiting (Current backends, Docker and Kubernetes, offer way more options than the PREvant configuration object allows). For example, PREvant was limited to self-contained applications where each microservice only relies on interactions via network API calls (REST, database connections, messaging, etc.) With this commit PREvant is now able to deploy application companions that are more powerful than the PREvant configuration in Kubernetes backends.

If `bootstrapping.containers` is defined, PREvant will start one or more containers on the infrastructure backend that are expected to generate Kubernetes manifests as output on standard out (stdout) that will be parsed by PREvant and supported are:

 - roles and role bindings
 - config maps and secrets
 - service accounts
 - persistent volume claims
 - services
 - pods, deployments, stateful sets, and jobs

Then before deploying these manifests PREvant merges all objects with the objects generated from the HTTP request payload. Thus you can add or overwrite configurations. For example, you can change the image used or an environment variable. If you overwrite any configuration the companion will be turned into an instance (as PREvant did before).

Ingresses won't be deployed if the bootstrap container outputs one of these. Instead they will be parsed and if they use the ingress class `nginx` they will be transformed into Traefik ingresses and middlewares so that the microservices will be available via web interface.

This approach make #143 obsolete and fixes #123

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +these use cases following sections provide example configurations.
```suggestion
these use cases the following sections provide example configurations.
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +Have a look at the [basic terminology](../README.md) what is a companion. For
```suggestion
Have a look at the [basic terminology](../README.md) to understand what a companion is. For
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +A simple but limited configuration of companions can be done via the
```suggestion
A simple, but limited configuration of companions can be done via the
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +If you want to include an OpenID provider for every application, you could use following configuration.
```suggestion
If you want to include an OpenID provider for every application, you could use the following configuration:
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +- `services`: An array of the services of the application. Each element has following structure:
```suggestion
- `services`: An array of the services of the application. Each element has the following structure:
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +- `isNotCompanion <type>` A conditional handlerbars block helper that checks if the given service type does not match any companion type.
```suggestion
PREvant provides some handlebars helpers which can be used to generate more complex configuration files. See handlebar's [block helper documentation](https://handlebarsjs.com/block_helpers.html) for more details.

- `{{#isCompanion <type>}}` A conditional handlebars block helper that checks if the given service type matches any companion type.
- `isNotCompanion <type>` A conditional handlebars block helper that checks if the given service type does not match any companion type.
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +The service-based companions works the in the same way as the application-based services. Make sure, that the `serviceName` is unique by using the handlebars templating.
```suggestion
The service-based companions work the in the same way as the application-based services. Make sure, that the `serviceName` is unique by using handlebars templating.
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +- `service`: The companion's service containing following fields:
```suggestion
- `service`: The companion's service containing the following fields:
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +`deploymentStrategy` offers following values and if a companion exists for an app following strategy will be applied:
```suggestion
`deploymentStrategy` offers the following values and if a companion exists for an app the following strategy will be applied:
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +`storageStrategy` offers following values to determine how storage is managed for a companion:
```suggestion
`storageStrategy` offers the following values to determine how storage is managed for a companion:
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +within the infrastructure (depicted by following image). PREvant's static
```suggestion
within the infrastructure (depicted by following the image). PREvant's static
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +  Make sure to put out YAML that is compatible with 1.1 and 1.2
```suggestion
  Make sure to output YAML that is compatible with 1.1 and 1.2
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +Following configuration block depicts that an image
```suggestion
The following configuration block depicts that an image
```

2024-01-22 09:38 UTC, aixigo-ohornischer commented on docs/companions.md
> +[Keycloak][keycloak]. Additionally, it is possible to passed additional
```suggestion
[Keycloak][keycloak]. Additionally, it is possible to pass additional
```

2024-01-23 13:59 UTC, schrieveslaach commented
@aixigo-ohornischer, thanks for proofing this PR.

2024-01-24 10:52 UTC, samuchila requested changes
Some minor typo's identified after reading the changes

2024-01-24 10:52 UTC, samuchila commented on docs/companions.md
> +[Keycloak][keycloak]. Additionally, it is possible to pasadditional arguments
```suggestion
[Keycloak][keycloak]. Additionally, it is possible to pass additional arguments
```

2024-01-24 10:52 UTC, samuchila commented on api/src/infrastructure/kubernetes/deployment_unit.rs
> +    async fn parse_unit_from_deploymen_stdout() {
```suggestion
    async fn parse_unit_from_deployment_stdout() {
```

2024-01-24 10:52 UTC, samuchila commented on api/src/infrastructure/kubernetes/infrastructure.rs
> +        deployabel_service: &DeployableService,
```suggestion
        deployable_service: &DeployableService,
```

2024-01-24 10:52 UTC, samuchila commented on api/src/infrastructure/kubernetes/payloads.rs
> +                    // TODO: how to get the if missing
I think this comment is incomplete here. Please expand on it for future tracking

2024-01-25 12:12 UTC, merged

2024-01-25 13:35 UTC, AnumDastgir commented on docs/companions.md
> +to the container than can be templated with [Handlebars][handlebars].
to the container (than->that) can be templated with [Handlebars][handlebars]